version: '3.8'  # Or whatever version you're using

services:
  backend:
    build:
      context: .  
      dockerfile: Dockerfile 
    image: lincoln1000/sil-backend:latest 
    container_name: sil-backend 
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      GHUB_CLIENT_ID: "${GHUB_CLIENT_ID}"
      GHUB_CLIENT_SECRET: "${GHUB_CLIENT_SECRET}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
    restart: always
