version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lincoln1000/sil-backend:latest
    container_name: sil-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GHUB_CLIENT_ID: ${GHUB_CLIENT_ID}
      GHUB_CLIENT_SECRET: ${GHUB_CLIENT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    restart: always

  postgres:
    image: postgres:13
    container_name: sil-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerrtyui
      POSTGRES_DB: sildb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
