services:
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    image: lincoln1000/sil-backend:latest
    container_name: sil-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
