version: '3.8'

services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile 
    image: lincoln1000/sil-backend:latest 
    container_name: sil-backend 
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  postgres:
    image: postgres:13
    container_name: sil-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerrtyui
      POSTGRES_DB: sildb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
