
services:
  backend:
    image: lincoln1000/backend:latest
    container_name: sil-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      GHUB_CLIENT_ID: "${GHUB_CLIENT_ID}"
      GHUB_CLIENT_SECRET: "${GHUB_CLIENT_SECRET}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
    restart: always
